"""initial schema

Revision ID: 20251212_1
Revises: 
Create Date: 2025-12-12 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20251212_1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('gcs_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Float(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='processingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.create_table('processing_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('roof_area_sqft', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('materials', postgresql.JSONB(astext_for_json=True), nullable=True),
    sa.Column('roof_features', postgresql.JSONB(astext_for_json=True), nullable=True),
    sa.Column('complexity_factors', postgresql.JSONB(astext_for_json=True), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('stages_completed', postgresql.JSONB(astext_for_json=True), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('ai_interpretation', sa.Text(), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_for_json=True), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_for_json=True), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_for_json=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_results_document_id'), 'processing_results', ['document_id'], unique=True)
    op.create_index(op.f('ix_processing_results_id'), 'processing_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_results_id'), table_name='processing_results')
    op.drop_index(op.f('ix_processing_results_document_id'), table_name='processing_results')
    op.drop_table('processing_results')
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###

    # Manually drop the ENUM type for full cleanup
    sa.Enum(name='processingstatus').drop(op.get_bind(), checkfirst=True)