version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roofing_database
    environment:
      - POSTGRES_DB=brant_roofing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - roofing_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d brant_roofing"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  roofing_network:
    driver: bridge
